#The strings containing the hangman himself, in 7 phases
#It begins with a lone noose, and progressively adds more body parts the more letters missed
#38 columns wide

class Hangman:

    def plusRightLeg(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       _             ")
        print("|                     /   \           ")
        print("|                     \   /           ")
        print("|                       -             ")
        print("|                    \  |  /          ")
        print("|                     \ | /           ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                      / \            ")
        print("|                     /   \           ")
        print("|                    /     \          ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")

    def plusLeftLeg(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       _             ")
        print("|                     /   \           ")
        print("|                     \   /           ")
        print("|                       -             ")
        print("|                    \  |  /          ")
        print("|                     \ | /           ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                      /              ")
        print("|                     /               ")
        print("|                    /                ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")

    def plusRightArm(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       _             ")
        print("|                     /   \           ")
        print("|                     \   /           ")
        print("|                       -             ")
        print("|                    \  |  /          ")
        print("|                     \ | /           ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")


    def plusLeftArm(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       _             ")
        print("|                     /   \           ")
        print("|                     \   /           ")
        print("|                       -             ")
        print("|                    \  |             ")
        print("|                     \ |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")
        

    def plusTorso(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       _             ")
        print("|                     /   \           ")
        print("|                     \   /           ")
        print("|                       -             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")

    def plusHead(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       _             ")
        print("|                     /   \           ")
        print("|                     \   /           ")
        print("|                       -             ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")

    def noose(blanks):
        print("")
        print("-------------------------             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                       |             ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|                                     ")
        print("|")
        print(str.format("|{0:^25}", blanks))
        print("-------------------------             ")
        
